### PR TITLE
Header integration into titlebar and other stuff.

### PR DESCRIPTION
**Pull request by Guerra24**
...and this *SHOULD* fix some problems with VS (nuget restore required after merge).

This updates *load all details* and *pin anime* pop-ups, forum, fixes the other anime list modes and adds reveal to some buttons that I forgot. Check commit messages for the other features, fixes and/or bugs.

### CODE REVIEW

**Comment by Drutol** [comment]
Sorry that I'm this dormant. I'll go through it once Christmas holidays start.

**Comment by Drutol** [comment]
Okay, I'm not sure I like this part
image
It's very small, empty...

This half looks much better though
image

**Comment by Drutol** [comment]
Integrating is okay, just I'm not really the fan of putting there too much content. We can make the left side stay as is for now but I'd really like to remove the header with username and current filter back where they were.

Search bar could stay there probably.

I've fixed some broken stuff like recommendations and characters... is anything else broken from MAL scraping standpoint?
Oh and they are releasing closed beta API mid-Feb so things gonna get hectic :)

**Comment by Drutol** [comment]
Also good job with somehow organising it somehow. I'm currently debating whether to make little backend revolution so this codebase isn't complete landfill... or make it just work with new MAL's apis. Don't know about motivation. Gotta update android now.

**Comment by Guerra24** [comment]
I'm not sure why it broke but the IP ban message is crashing the app, it fails in the *UWP DispatcherAdapter* when creating the grid because is not in the correct thread, I can probably fix it but I'm scared of breaking something in XShared. I'm going to move the username and filter to match the right side. Also, when merging this please delete the conflicting files (.nuget.props), they are the cause of the issues with VS.

**Comment by Drutol** [comment]
Okay, the IP ban message is caused by MAL's bug. It just triggered for me and I had to restart my router, but I had no crash. I'll look into this adapter then.

**Comment by Drutol** [comment]
I'm aiming for updates this weekend :)

**Comment by Guerra24** [comment]
What do you think?

image

**Comment by Guerra24** [comment]
Actually, what do you think about making the integrated header optional so the users who prefer to have more space can enable it?

**Comment by Drutol** [comment]
Throwing in additional setting shouldn't be much of a problem. Depends on how are you doing it, I didn't look into it yet.

It still looks a bit off, what if we made the middle part acrylic too and gave it a bit darker tone on the whole length? It may not follow the guidelines/examples 1:1 but it may remove the sense of emptiness?

**Comment by Drutol** [comment]
Hmm apparently the branch github created for me isn't tied to  this PR... I'll merge it manually.

**Pull request merged**
