### PR TITLE
Make my life easier :)

### PR DESCRIPTION
**Pull request by Guerra24**
Please 🙏

### CODE REVIEW

**Comment by Guerra24** [comment]
Thanks! 😄

**Comment by Drutol** [comment]
Sure, now I'm having issues building the packages... kill me plz

**Comment by Guerra24** [comment]
A full package restore is need to restore the local files.

**Comment by Drutol** [comment]
I rather mean some strange errors like `MSBUILD : error : CA0055 : Could not identify platform for <path/file.exe>` and `CA0052 : No targets were selected`... first time seeing them xd

**Comment by Guerra24** [comment]
Other way is to delete and clone (remember to save the secrets file).

**Comment by Drutol** [comment]
You've gotten such errors previously?

**Comment by Guerra24** [comment]
Yes, every time I pull something from the repo it broke my local copy.

**Comment by Drutol** [comment]
Apparently it was something with roslyn code  analysers from .Net Core 2.0... fixed

**Pull request merged**
