### PR TITLE
Maintenance PR

### PR DESCRIPTION
**Pull request by Guerra24**
- Upped SDKs.
- Updated all libs, except the ones used in android. Related to this, the android project might fail due to CommonServiceLocator missing, add the lib manually to fix.
- Fixed blurry images in grid view.
- Fixed some elements with wrong size.
- Added reveal to settings pages.
- Testing Connected Animations, currently only use in the forums index to board.

I'm going to work in the mobile version now, don't merge until I commit that.

### CODE REVIEW

**Comment by Drutol** [comment]
Sitting down to it now :)

**Comment by Drutol** [comment]
I think I'll migrate shared projects do .NET standard. I feel like cleaning up a bit ^^

**Comment by Drutol** [comment]
Hmm, you did something strange to UWP.Adapters?

**Comment by Guerra24** [comment]
Not at code level, just removed/moved some duplicated nuget packages.

**Comment by Drutol** [comment]
Damn... it's complete mess... nothing has its nugets xd

**Comment by Guerra24** [comment]
Weird... after that it keep compiling correctly so I assumed it was OK.

**Comment by Drutol** [comment]
I don't even know how to fix it now without recreating all UWP ClassLibrary projects. It just doesn't see `System` namespace. And there's no single nuget installed.

**Comment by Drutol** [comment]
I'm going back to master to fix some things in shared then.

**Comment by Guerra24** [comment]
I'm going to rollback the project files and (if vs is not an idiot) should fix this.

**Comment by Drutol** [comment]
Yeah, something is fishy.

**Comment by Drutol** [comment]
Maybe just leave the nugets? I'll clear them up when porting to Net standard.

**Comment by Drutol** [comment]
image

It's not gonna build.

**Comment by Drutol** [comment]
Do you have newest VS?

**Comment by Guerra24** [comment]
Wait what, I've added the nugets. Yes, I'm using VS 15.6.4
img

**Comment by Drutol** [comment]
Hmm, maybe github is doing some peculiar things... I see packages.config on your repo but it's no on branch.

**Comment by Drutol** [comment]
Damn, github got some cancer, after pulling branch again it worked -.-

**Comment by Drutol** [comment]
I'm not sure about these spinners on grid items when loading image. They just flash for a split second most of the time.

**Pull request merged**
